yum install -y binutils
yum install -y elfutils-libelf
yum install -y elfutils-libelf-devel
yum install -y fontconfig
yum install -y gcc
yum install -y gcc
yum install -y glibc
yum install -y glibc-devel
yum install -y ksh
yum install -y libnsl2
yum install -y libX11
yum install -y libXau
yum install -y libXaw
yum install -y libXi
yum install -y libXrender
yum install -y libXtst
yum install -y libaio
yum install -y libaio-devel
yum install -y libattr-devel
yum install -y libgcc
yum install -y libgfortran
yum install -y libibverbs
yum install -y libnsl
yum install -y librdmacm
yum install -y libstdc
yum install -y libstdc
yum install -y libxcb
yum install -y make
yum install -y net-tools
yum install -y pam
yum install -y pam-devel
yum install -y policycoreutils
yum install -y policycoreutils-python-utils-2.9-9.el8.noarch
yum install -y smartmontools
yum install -y sysstat
yum install -y xorg
yum install -y x11
